name: CI Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - deploy

jobs:
  "run-jest-tests":
    runs-on: cs5500-self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Navigate to Server Directory and Install Dependencies
        working-directory: server
        run: npm install
        shell: bash

      - name: Run Tests
        working-directory: server
        run: npm run test
        env:
          NODE_ENV: test
        shell: bash

  "run-cypress-tests":
    runs-on: cs5500-self-hosted
    needs: "run-jest-tests"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies (Server)
        working-directory: server
        run: npm install
        shell: bash

      - name: Install Dependencies (Client)
        working-directory: client
        run: npm install
        shell: bash

      - name: Start Server
        working-directory: server
        run: |
          npm start &
        env:
          PORT: 8000
          NODE_ENV: test
        shell: bash

      - name: Start Client
        working-directory: client
        run: |
          npm start &
        env:
          PORT: 3000
        shell: bash

      - name: Wait for Server and Client to Start
        run: npx wait-on http://localhost:8000 http://localhost:3000
        shell: bash

      - name: Run Cypress Tests
        working-directory: client
        run: npx cypress run --spec cypress/e2e/**/*.feature
        env:
          NODE_ENV: test
        shell: bash
