name: Prepare Database

on:
  push:
    branches:
      - deploy

jobs:
  "setup-database":
    runs-on: cs5500-self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Navigate to Server Directory and Install Dependencies
        working-directory: server
        run: npm install

      - name: Delete Old Database
        working-directory: server
        run: npm run remove_db -- "mongodb://127.0.0.1:27017/stackUnderflow"

      - name: Seed Database
        working-directory: server
        run: npm run populate_db -- "mongodb://127.0.0.1:27017/stackUnderflow"
